# Generated by Django 3.1.4 on 2022-03-02 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('runtime', models.FloatField()),
                ('genre', models.CharField(choices=[('comedy', 'comedy'), ('action', 'action'), ('drama', 'drama')], max_length=25)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='media')),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.actor')),
            ],
        ),
    ]
