# Generated by Django 3.1.4 on 2022-03-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
