# Generated by Django 3.1.4 on 2022-03-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='file',
        ),
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
